name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'UAT Image Tag to deploy'
        required: true
        default: 'warning'
      waitForService:
        description: 'Wait for cluster to finish deployment?'
        required: true
        default: 'true'
        type: boolean
jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: UAT
    steps:         
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "This is the first step in the first job (build)"

  deploy:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Tarea de Deploy
        id: this-is-my-id
        run: |
          #This is a sample 
          echo "This is the first step in the second job (deploy)"
