name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build System Image
      run: docker build . --file system-image.dockerfile --tag fyfsystemimage:latest
      
    - name: Build Distribution Image
      run: docker build . --file distribution-image.dockerfile --tag fyfdistributionimage:latest
