name: Deploy workflow

on:
  workflow_call:
    inputs:
      imageTag:
        description: 'UAT Image Tag to deploy'
        required: true
        default: 'warning'
        type: string
      waitForService:
        description: 'Wait for cluster to finish deployment?'
        required: true
        default: true
        type: boolean

jobs:  
  build:
    runs-on: ubuntu-latest
    environment: UAT
    concurrency: UATD
    steps:         
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "This is the first step in the second workflow. The image tag is ${{ inputs.imageTag }}"
          
      - name: Tarea de Deploy
        id: this-is-my-id
        run: |
          #This is a sample 
          echo "This is the second step in the second job. The waitForService is ${{ inputs.waitForService }}"
